###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
## DEPL.TYPE
##  patterns: foundation,workflow
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba-test2
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 23.0.2
spec:

  appVersion: 23.0.2
  ibm_license: accept

  shared_configuration:
    sc_deployment_fncm_license: "non-production"
    sc_deployment_baw_license: "non-production"
    sc_deployment_license: "non-production"
    sc_deployment_context: "CP4A"
    sc_image_repository: cp.icr.io
    root_ca_secret: icp4a-root-ca
    sc_deployment_patterns: "foundation,workflow"
    sc_optional_components: ""
    sc_deployment_type: "Production"
    sc_deployment_platform: "OCP"
    sc_deployment_profile_size: "small"
    sc_ingress_enable: false
    trusted_certificate_list: []
    storage_configuration:
      sc_slow_file_storage_classname: "managed-nfs-storage"
      sc_medium_file_storage_classname: "managed-nfs-storage"
      sc_fast_file_storage_classname: "managed-nfs-storage"
      sc_block_storage_classname: "thin-csi"
    sc_iam:
      default_admin_username: "cpadmin"
    enable_fips: false
    #sc_run_as_user:
    sc_egress_configuration:
      # set false to enable outbout access
      sc_restricted_internet_access: false
    #  sc_api_namespace:
    #  sc_api_port:
    #  sc_dns_namespace:
    #  sc_dns_port:
    #sc_drivers_url:
    sc_content_initialization: true
    sc_content_verification: false
    encryption_key_secret: ibm-iaws-shared-key-secret
    image_pull_secrets:
      - ibm-entitlement-key
    no_log: false
    show_sensitive_log: true

  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_server: "vuxprod-ldap.cp4ba-test2.svc.cluster.local"
    lc_ldap_port: "389"
    lc_bind_secret: "ldap-bind-test2"
    lc_ldap_base_dn: "dc=vuxprod,dc=net"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: ""
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "dc=vuxprod,dc=net"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(&(cn=%v)(objectclass=groupOfNames))"
    lc_ldap_group_member_id_map: "memberof:member"
    lc_ldap_recursive_search: true
    lc_enable_pagination: false
    lc_pagination_size: 4500     
    custom:
      lc_user_filter: "(&(cn=%v)(objectclass=person))"
      lc_group_filter: "(&(cn=%v)(objectclass=groupOfNames))"

  datasource_configuration:
    dc_ssl_enabled: false

    dc_icn_datasource:
      dc_database_type: "postgresql"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "my-postgres-for-cp4ba-rw.cp4ba-test2.svc.cluster.local"
      database_port: "5432"
      database_name: "test2_icn"
      database_ssl_secret_name: ""
      #dc_hadr_validation_timeout: 15
      #dc_hadr_standby_servername: ""
      #dc_hadr_standby_port: ""
      #dc_hadr_retry_interval_for_client_reroute: 15
      #dc_hadr_max_retries_for_client_reroute: 3

  # IBM Application Engine configuration
  application_engine_configuration:
    - name: workspace1 
      admin_secret_name: "icp4adeploy-workspace1-aae-app-engine-admin-secret"
      admin_user: "cp4admin"
      database:
        host: "my-postgres-for-cp4ba-rw.cp4ba-test2.svc.cluster.local"
        port: "5432"      
        name: "test2_aedb_1"
        type: postgresql
        enable_ssl: false
        db_cert_secret_name: ""
      session:
        use_external_store: false

  # IBM Business Automation Workflow configuration
  baw_configuration:
    - name: baw1 
      capabilities: "workflow"
      host_federated_portal: true
      admin_user: "cp4admin"
      database:
        enable_ssl: false
        db_cert_secret_name: ""
        type: "postgresql"
        server_name: "my-postgres-for-cp4ba-rw.cp4ba-test2.svc.cluster.local"
        port: "5432"
        database_name: "test2_baw_1"
        secret_name: "test2-baw1-server-db-secret"
        use_custom_jdbc_drivers: false
        #hadr:
        #  standbydb_host: ""
        #  standbydb_port: ""
      #content_integration:
      #  domain_name: "P8DOMAIN"
      #  object_store_name: "BAWINS1DOCS"
      #case:
      #  domain_name: "P8DOMAIN"
      #  object_store_name_dos: "BAWINS1DOS"
      #  tos_list:
      #    - object_store_name: "BAWINS1TOS"
      security_context:
        selinux_options:
        fs_groupchangepolicy:
      # Production, Staging, Test, Development
      env_type: Test
      resources:
        limits:
          cpu: "2000m"
          memory: "3096Mi"
        requests:
          cpu: "500m"
          memory: "1048Mi"
      logs:
        trace_specification: "*=info"
