###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
## DEPL.TYPE
##  patterns: foundation,content,workflow
##  optional components: cmis
## TBM
##  - 
##  - 
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: ${CP4BA_INST_CR_NAME}
  namespace: ${CP4BA_INST_NAMESPACE}
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: ${CP4BA_INST_RELEASE}
spec:

  appVersion: ${CP4BA_INST_APPVER}
  ibm_license: accept

  shared_configuration:
    sc_deployment_fncm_license: "non-production"
    sc_deployment_baw_license: "non-production"
    sc_deployment_license: "non-production"
    sc_deployment_context: "CP4A"
    sc_image_repository: cp.icr.io
    root_ca_secret: icp4a-root-ca
    sc_deployment_patterns: "foundation,content,workflow"
    sc_optional_components: "cmis"
    sc_deployment_type: "Production"
    sc_deployment_platform: "OCP"
    sc_deployment_profile_size: "small"
    sc_ingress_enable: false
    trusted_certificate_list: []
    storage_configuration:
      sc_slow_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_medium_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_fast_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_block_storage_classname: "${CP4BA_INST_SC_BLOCK}"
    sc_iam:
      default_admin_username: "${CP4BA_INST_IAM_ADMIN_USER}"
    enable_fips: false
    sc_run_as_user:
    sc_egress_configuration:
      sc_restricted_internet_access: false
      sc_api_namespace:
      sc_api_port:
      sc_dns_namespace:
      sc_dns_port:
    sc_drivers_url:
    sc_content_initialization: true
    sc_content_verification: false
    encryption_key_secret: ibm-iaws-shared-key-secret
    image_pull_secrets:
      - ibm-entitlement-key
    no_log: false
    show_sensitive_log: true

  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_server: "${CP4BA_INST_LDAP_HOST}"
    lc_ldap_port: "${CP4BA_INST_LDAP_PORT}"
    lc_bind_secret: "${CP4BA_INST_LDAP_SECRET}"
    lc_ldap_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: ""
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(&(cn=%v)(objectclass=groupOfNames))"
    lc_ldap_group_member_id_map: "memberof:member"
    lc_ldap_recursive_search: true
    lc_enable_pagination: false
    lc_pagination_size: 4500     
    custom:
      lc_user_filter: "(&(cn=%v)(objectclass=person))"
      lc_group_filter: "(&(cn=%v)(objectclass=groupOfNames))"

  datasource_configuration:
    dc_ssl_enabled: false

    dc_icn_datasource:
      dc_database_type: "postgresql"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}icn"
      database_ssl_secret_name: ""
      dc_hadr_validation_timeout: 15
      dc_hadr_standby_servername: ""
      dc_hadr_standby_port: ""
      dc_hadr_retry_interval_for_client_reroute: 15
      dc_hadr_max_retries_for_client_reroute: 3

    dc_gcd_datasource:
      dc_database_type: "postgresql"
      dc_common_gcd_datasource_name: "FNGCDDS"
      dc_common_gcd_xa_datasource_name: "FNGCDDSXA"
      database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
      database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}gcd"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_ssl_secret_name: ""
      dc_hadr_validation_timeout: 15
      dc_hadr_standby_servername: ""
      dc_hadr_standby_port: ""
      dc_hadr_retry_interval_for_client_reroute: 15
      dc_hadr_max_retries_for_client_reroute: 3

    dc_os_datasources:
      - dc_database_type: "postgresql"
        dc_os_label: ""
        dc_common_os_datasource_name: "FNOS1DS"
        dc_common_os_xa_datasource_name: "FNOS1DSXA"
        database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
        database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}os1"
        database_port: "${CP4BA_INST_DB_SERVER_PORT}"
        database_ssl_secret_name: ""
        dc_hadr_validation_timeout: 15
        dc_hadr_standby_servername: ""
        dc_hadr_standby_port: ""
        dc_hadr_retry_interval_for_client_reroute: 15
        dc_hadr_max_retries_for_client_reroute: 3

      - dc_database_type: "postgresql"
        dc_os_label: ""
        dc_common_os_datasource_name: "BAWINS1DOCS"
        dc_common_os_xa_datasource_name: "BAWINS1DOCSXA"
        database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
        database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}bawdocs"
        database_port: "${CP4BA_INST_DB_SERVER_PORT}"
        database_ssl_secret_name: ""
        dc_hadr_validation_timeout: 15
        dc_hadr_standby_servername: ""
        dc_hadr_standby_port: ""
        dc_hadr_retry_interval_for_client_reroute: 15
        dc_hadr_max_retries_for_client_reroute: 3

      - dc_database_type: "postgresql"
        dc_os_label: ""
        dc_common_os_datasource_name: "BAWINS1DOS"
        dc_common_os_xa_datasource_name: "BAWINS1DOSXA"
        database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
        database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}bawdos"
        database_port: "${CP4BA_INST_DB_SERVER_PORT}"
        database_ssl_secret_name: ""
        dc_oracle_os_jdbc_url: ""
        dc_hadr_validation_timeout: 15
        dc_hadr_standby_servername: ""
        dc_hadr_standby_port: ""
        dc_hadr_retry_interval_for_client_reroute: 15
        dc_hadr_max_retries_for_client_reroute: 3

      - dc_database_type: "postgresql"
        dc_os_label: ""
        dc_common_os_datasource_name: "BAWINS1TOS"
        dc_common_os_xa_datasource_name: "BAWINS1TOSXA"
        database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
        database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}bawtos"
        database_port: "${CP4BA_INST_DB_SERVER_PORT}"
        database_ssl_secret_name: ""
        dc_hadr_validation_timeout: 15
        dc_hadr_standby_servername: ""
        dc_hadr_standby_port: ""
        dc_hadr_retry_interval_for_client_reroute: 15
        dc_hadr_max_retries_for_client_reroute: 3

  application_engine_configuration:
    - name: ${CP4BA_INST_AE_1_NAME} 
      admin_secret_name: "${CP4BA_INST_AE_1_AD_SECRET_NAME}"
      admin_user: "${CP4BA_INST_AE_1_ADMIN_USER}"
      database:
        host: "${CP4BA_INST_AE_1_DB_HOST}"
        port: "${CP4BA_INST_AE_1_DB_PORT}"      
        name: "${CP4BA_INST_AE_1_DB_NAME}"
        type: postgresql
        enable_ssl: false
        db_cert_secret_name: ""
      session:
        use_external_store: false

  # IBM FileNet Content Manager initialize configuration
  initialize_configuration:
    ic_ldap_creation:
      ic_ldap_admin_user_name:
        - "${CP4BA_INST_IAM_ADMIN_USER}"
      ic_ldap_admins_groups_name:
        - "${CP4BA_INST_IAM_ADMIN_GROUP}"
    ic_domain_creation:
      domain_name: "P8DOMAIN"
      encryption_key: "128"
    ic_obj_store_creation:
      object_stores:
        - oc_cpe_obj_store_display_name: "OS01"
          oc_cpe_obj_store_symb_name: "OS01"
          oc_cpe_obj_store_conn:
            name: "objectstore1_connection"
            dc_os_datasource_name: "FNOS1DS"
            dc_os_xa_datasource_name: "FNOS1DSXA"
          oc_cpe_obj_store_admin_user_groups:
            - "${CP4BA_INST_PAKBA_ADMIN_USER}"
            - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        - oc_cpe_obj_store_display_name: "BAWINS1DOCS"
          oc_cpe_obj_store_symb_name: "BAWINS1DOCS"
          oc_cpe_obj_store_conn:
            name: "DOCS_connection"
            dc_os_datasource_name: "BAWINS1DOCS"
            dc_os_xa_datasource_name: "BAWINS1DOCSXA"
          oc_cpe_obj_store_admin_user_groups:
            - "${CP4BA_INST_PAKBA_ADMIN_USER}"
            - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        - oc_cpe_obj_store_display_name: "BAWINS1DOS"
          oc_cpe_obj_store_symb_name: "BAWINS1DOS"
          oc_cpe_obj_store_conn:
            name: "DOS_connection"
            dc_os_datasource_name: "BAWINS1DOS"
            dc_os_xa_datasource_name: "BAWINS1DOSXA"
          oc_cpe_obj_store_admin_user_groups:
            - "${CP4BA_INST_PAKBA_ADMIN_USER}"
            - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
        - oc_cpe_obj_store_display_name: "BAWINS1TOS"
          oc_cpe_obj_store_symb_name: "BAWINS1TOS"
          oc_cpe_obj_store_conn:
            name: "TOS_connection"
            dc_os_datasource_name: "BAWINS1TOS"
            dc_os_xa_datasource_name: "BAWINS1TOSXA"
          oc_cpe_obj_store_admin_user_groups:
            - "${CP4BA_INST_PAKBA_ADMIN_USER}"
            - "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
          oc_cpe_obj_store_enable_workflow: true
          oc_cpe_obj_store_workflow_data_tbl_space: "testbawtos_tbs"
          oc_cpe_obj_store_workflow_admin_group: "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
          oc_cpe_obj_store_workflow_config_group: "${CP4BA_INST_PAKBA_ADMIN_GROUP}"
          oc_cpe_obj_store_workflow_pe_conn_point_name: "pe_conn_bawtos"
    #ic_icn_init_info:
    #  icn_repos:
    #    - add_repo_id: "demo_repo1"
    #      add_repo_ce_wsi_url: "https://{{ meta.name }}-cpe-stateless-svc.{{ meta.namespace }}.svc:9443/wsi/FNCEWS40MTOM/"
    #      add_repo_os_sym_name: "OS01"
    #      add_repo_os_dis_name: "OS01"
    #      add_repo_workflow_enable: false
    #      add_repo_work_conn_pnt: "pe_conn_os1:1"
    #      add_repo_protocol: "FileNetP8WSI"
    #  icn_desktop:
    #    - add_desktop_id: "demo"
    #      add_desktop_name: "icn_desktop"
    #      add_desktop_description: "This is ICN desktop"
    #      add_desktop_is_default: false
    #      add_desktop_repo_id: "demo_repo1"
    #      add_desktop_repo_workflow_enable: false
  
  # IBM FileNet Content Manager Verification configuration
  #verify_configuration:
  #  vc_cpe_verification:
  #    vc_cpe_folder:
  #      - folder_cpe_obj_store_name: "OS01"
  #        folder_cpe_folder_path: "/TESTFOLDER"
  #    vc_cpe_document:
  #      - doc_cpe_obj_store_name: "OS01"
  #        doc_cpe_folder_name: "/TESTFOLDER"
  #        doc_cpe_doc_title: "test_title"
  #        DOC_CPE_class_name: "Document"
  #        doc_cpe_doc_content: "This is a simple document test"
  #        doc_cpe_doc_content_name: "doc_content_name"
  #    vc_cpe_cbr:
  #      - cbr_cpe_obj_store_name: "OS01"
  #        cbr_cpe_class_name: "Document"
  #        cbr_cpe_search_string: "is a simple"
  #    vc_cpe_workflow:
  #      - workflow_cpe_enabled: false
  #        workflow_cpe_connection_point: "pe_conn_os1"
  #  vc_icn_verification:
  #    - vc_icn_repository: "demo_repo1"
  #      vc_icn_desktop_id: "demo"

  # IBM Business Automation Workflow configuration
  baw_configuration:
    - name: ${CP4BA_INST_BAW_1_NAME} 
      capabilities: "workflow"
      host_federated_portal: true
      admin_user: "${CP4BA_INST_PAKBA_ADMIN_USER}"
      database:
        enable_ssl: false
        db_cert_secret_name: ""
        type: "postgresql"
        server_name: "${CP4BA_INST_BAW_1_DB_HOST}"
        port: "${CP4BA_INST_BAW_1_DB_PORT}"
        database_name: "${CP4BA_INST_BAW_1_DB_NAME}"
        secret_name: "${CP4BA_INST_BAW_1_DB_SECRET}"
        use_custom_jdbc_drivers: false
        hadr:
          standbydb_host: ""
          standbydb_port: ""
      content_integration:
        domain_name: "P8DOMAIN"
        object_store_name: "BAWINS1DOCS"
      case:
        domain_name: "P8DOMAIN"
        object_store_name_dos: "BAWINS1DOS"
        tos_list:
          - object_store_name: "BAWINS1TOS"
      security_context:
        selinux_options:
        fs_groupchangepolicy:
      # Production, Staging, Test, Development
      env_type: Test
      resources:
        limits:
          cpu: "${CP4BA_INST_BAW_1_LIMITS_CPU}"
          memory: "${CP4BA_INST_BAW_1_LIMITS_MEMORY}"
        requests:
          cpu: "500m"
          memory: "1048Mi"
      logs:
        trace_specification: "${CP4BA_INST_BAW_1_LOGS_TRACE}"
