###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
## DEPL.TYPE
##  patterns: foundation,workflow
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: ${CP4BA_INST_CR_NAME}
  namespace: ${CP4BA_INST_NAMESPACE}
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: ${CP4BA_INST_RELEASE}
spec:

  appVersion: ${CP4BA_INST_APPVER}
  ibm_license: accept

  shared_configuration:
    sc_deployment_fncm_license: "non-production"
    sc_deployment_baw_license: "non-production"
    sc_deployment_license: "non-production"
    sc_deployment_context: "CP4A"
    sc_image_repository: cp.icr.io
    root_ca_secret: icp4a-root-ca
    sc_deployment_patterns: "foundation,workflow"
    sc_optional_components: ""
    sc_deployment_type: "Production"
    sc_deployment_platform: "OCP"
    sc_deployment_profile_size: "small"
    sc_ingress_enable: false
    trusted_certificate_list: []
    storage_configuration:
      sc_slow_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_medium_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_fast_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_block_storage_classname: "${CP4BA_INST_SC_BLOCK}"
    sc_iam:
      default_admin_username: "${CP4BA_INST_IAM_ADMIN_USER}"
    enable_fips: false
    #sc_run_as_user:
    sc_egress_configuration:
      # set false to enable outbout access
      sc_restricted_internet_access: false
    #  sc_api_namespace:
    #  sc_api_port:
    #  sc_dns_namespace:
    #  sc_dns_port:
    #sc_drivers_url:
    sc_content_initialization: false
    sc_content_verification: false
    encryption_key_secret: ibm-iaws-shared-key-secret
    image_pull_secrets:
      - ibm-entitlement-key
    no_log: false
    show_sensitive_log: true

  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_server: "${CP4BA_INST_LDAP_HOST}"
    lc_ldap_port: "${CP4BA_INST_LDAP_PORT}"
    lc_bind_secret: "${CP4BA_INST_LDAP_SECRET}"
    lc_ldap_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: ""
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "${CP4BA_INST_LDAP_BASE_DOMAIN}"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(&(cn=%v)(objectclass=groupOfNames))"
    lc_ldap_group_member_id_map: "memberof:member"
    lc_ldap_recursive_search: true
    lc_enable_pagination: false
    lc_pagination_size: 4500     
    custom:
      lc_user_filter: "(&(cn=%v)(objectclass=person))"
      lc_group_filter: "(&(cn=%v)(objectclass=groupOfNames))"

  datasource_configuration:
    dc_ssl_enabled: false

    dc_icn_datasource:
      dc_database_type: "postgresql"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "${CP4BA_INST_DB_SERVER_NAME}"
      database_port: "${CP4BA_INST_DB_SERVER_PORT}"
      database_name: "${CP4BA_INST_DB_FAMILY_PREFIX}icn"
      database_ssl_secret_name: ""
      #dc_hadr_validation_timeout: 15
      #dc_hadr_standby_servername: ""
      #dc_hadr_standby_port: ""
      #dc_hadr_retry_interval_for_client_reroute: 15
      #dc_hadr_max_retries_for_client_reroute: 3

  # IBM Application Engine configuration
  application_engine_configuration:
    - name: ${CP4BA_INST_AE_1_NAME} 
      admin_secret_name: "${CP4BA_INST_AE_1_AD_SECRET_NAME}"
      admin_user: "${CP4BA_INST_AE_1_ADMIN_USER}"
      database:
        host: "${CP4BA_INST_AE_1_DB_HOST}"
        port: "${CP4BA_INST_AE_1_DB_PORT}"      
        name: "${CP4BA_INST_AE_1_DB_NAME}"
        type: postgresql
        enable_ssl: false
        db_cert_secret_name: ""
      session:
        use_external_store: false

  # IBM Business Automation Workflow configuration
  baw_configuration:
    - name: ${CP4BA_INST_BAW_1_NAME} 
      capabilities: "workflow"
      host_federated_portal: true
      admin_user: "${CP4BA_INST_PAKBA_ADMIN_USER}"
      database:
        enable_ssl: false
        db_cert_secret_name: ""
        type: "postgresql"
        server_name: "${CP4BA_INST_BAW_1_DB_HOST}"
        port: "${CP4BA_INST_BAW_1_DB_PORT}"
        database_name: "${CP4BA_INST_BAW_1_DB_NAME}"
        secret_name: "${CP4BA_INST_BAW_1_DB_SECRET}"
        use_custom_jdbc_drivers: false
        #hadr:
        #  standbydb_host: ""
        #  standbydb_port: ""
      #content_integration:
      #  domain_name: "P8DOMAIN"
      #  object_store_name: "BAWINS1DOCS"
      #case:
      #  domain_name: "P8DOMAIN"
      #  object_store_name_dos: "BAWINS1DOS"
      #  tos_list:
      #    - object_store_name: "BAWINS1TOS"
      security_context:
        selinux_options:
        fs_groupchangepolicy:
      # Production, Staging, Test, Development
      env_type: Test
      resources:
        limits:
          cpu: "${CP4BA_INST_BAW_1_LIMITS_CPU}"
          memory: "${CP4BA_INST_BAW_1_LIMITS_MEMORY}"
        requests:
          cpu: "500m"
          memory: "1048Mi"
      logs:
        trace_specification: "${CP4BA_INST_BAW_1_LOGS_TRACE}"
